### PR TITLE
Add fix to citation_list

### LINKED ISSUE #836: 🐛 publishing with many references causing an `undefined` error
### URL of the Page

_No response_

### What happened?

Somebody reported that they are trying to publish a module but it failed. 

```
TypeError: Cannot read properties of undefined (reading 'map')
    at eval (webpack-internal:///./app/api/test.ts:87:35)
    at Array.map (<anonymous>)
    at handler (webpack-internal:///./app/api/test.ts:68:145)
    at async Object.apiResolver (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/api-utils.js:114:13)
    at async DevServer.handleApiRequest (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:763:9)
    at async Object.fn (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:654:37)
    at async Router.execute (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/router.js:206:32)
    at async DevServer.run (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:831:29)
    at async DevServer.handleRequest (/Users/chjh/git/libscie/ResearchEquals.com/node_modules/next/dist/server/next-server.js:295:20)
```

Debugging and fixing as this is a very specific issue - creating an issue to track the problem. I will try to document what the issue is so we can reference it as we make the publishing process more robust.

### Steps to reproduce

n/a

### What browser(s) did you use?

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chartgerink**
This PR adjusts the `citation_list` to be able to deal with absent authors. This was an issue reported by a user.

Can be tested with `10.1007/978-981-10-1607-3`.

Fixes #836.

### CODE REVIEW

File: app/core/crossref/citation_list.tsx [hunk 1]
```diff
@@ -55,6 +55,7 @@ const citation_list = ({ citations }: { citations: Cite[] }): CitationList => {
     name: "citation_list",
     children: citations.map((citation, index) => {
       const { publishedWhere, authors, title, prefix, suffix, publishedAt } = citation
+      console.log(authors)
```
Comment (nsunami) [inline app/core/crossref/citation_list.tsx:58]: Shall we remove this console output?

**Review by nsunami — APPROVED** [review]
Checked on my local and review that it works!

image


I had a small comment about the console logging—but I will leave it up to you to fix or not before you merge. 

LGTM! ✅ 🎉

File: app/core/crossref/citation_list.tsx (hunk 1 above)
Comment (chartgerink) [reply app/core/crossref/citation_list.tsx:58]: Thanks!

Suggestions are great for these kinds of fixes btw

```suggestion

```
