### PR TITLE
Make the "Got it!" text clickable in the email onboarding quest

### LINKED ISSUE #738: Cannot click "Got it" link after agreeing to receive email notifications  🐛
### URL of the Page

https://www.researchequals.com/dashboard

### What happened?

I noticed that after clicking yes 👍 to receive email notification, I cannot click "Got it!" button on the confirmation (as below). 

image

### Steps to reproduce

1. Go to dashboard with an account that has not completed the onboarding quest for email notifications
2. Select "Yes" to receive email notifications
3. Cannot click "Got it!" (I expected that we can close the card by clicking this.)

### What browser(s) did you use?

Chrome

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nsunami**
This PR makes the "Got it!" text clickable in the email onboarding quest. Clicking the link will hide the quest card.  Fixes #738.

This PR uses a stateful value (`showCard`) to track the state of the card (show/hide).  This PR also converts the ternary operator style into the short-circuit style, as mentioned in #546.

### CODE REVIEW

File: app/core/components/OnboardingQuests.jsx [hunk 1]
```diff
@@ -300,11 +308,7 @@ const OnboardingAvatar = ({ data, expire, signature, refetch }) => {
         >
           <div className="flex flex-grow">
             <div className="">
-              <UserAvatar
-                size={32}
-                className="h-5 w-5 text-indigo-400 dark:text-indigo-200"
-                aria-hidden="true"
-              />
+              <UserAvatar size={32} className="h-5 w-5 text-indigo-400 dark:text-indigo-200" />
```
Comment (chartgerink) [inline app/core/components/OnboardingQuests.jsx:311]: Could you please tell me why this is edited? This seems like an arbitrary edit and out of scope for this PR. 

It is good practice to not make edits unrelated to the scope as it is high-risk for creating problems/confusion. 

for what it's worth - `aria-hidden` is used to remove icons (among other things) from screenreaders. This removal needs to be undone because it's necessary here.

**Review by chartgerink — CHANGES_REQUESTED** [review]

File: app/core/components/OnboardingQuests.jsx (hunk 1 above)
Comment (chartgerink) [reply app/core/components/OnboardingQuests.jsx:311]:
```suggestion
              <UserAvatar size={32} className="h-5 w-5 text-indigo-400 dark:text-indigo-200" aria-hidden="true" />
```

File: app/core/components/OnboardingQuests.jsx [hunk 2]
```diff
@@ -138,7 +141,14 @@ const OnboardingEmailAccept = ({ data }) => {
...
               {isSuccess ? (
-                <p className="whitespace-nowrap font-medium  underline">Got it!</p>
+                <p className="whitespace-nowrap font-medium underline">
+                  <a
+                    className="hover:cursor-pointer hover:text-blue-600"
+                    onClick={() => setShowCard(false)}
+                  >
+                    Got it!
+                  </a>
+                </p>
```
[the remark this answers is not in the document]
Comment (nsunami) [reply app/core/components/OnboardingQuests.jsx:151]: Got it! I think for me an underlined text implies an action/a-tag visually, but in the code that makes sense. 👍

File: app/core/components/OnboardingQuests.jsx (hunk 1 above)
Comment (nsunami) [reply app/core/components/OnboardingQuests.jsx:309]: @chartgerink I don't remember actively removing this. Thanks for adding this back.

I 100% agree with not making arbitrary edits! Thanks for catching.

And thanks for explaining what `aria-hidden` does.

**Review by chartgerink — APPROVED** [review]
